### ISSUE TITLE
Utils can't find local cached input file by filename

### ISSUE THREAD

**Issue by baristarlin** [valohai/valohai-utils#91]
When using datums as default input values you get a error message  "No connection adapters were found for datum" even if the file is locally available. 

Current workaround: local file needs to be renamed to the datum UID and without a file extension.

It would be fantastic if utils could find the file based on the filename.

```
mydata = {
    'train': 'datum://0181663c-4305-2cf0-298e-eb670f5c06dc',
    'test': 'datum://0181663c-4194-d20e-a804-7a8b4bfe1131'
}
```

**Comment by magdapoppins** [comment]
Just to check that I'm following - if there is a file at the given path, we would make a call to roi to create an actual datum of it and then add the generated ID to the yaml?

Since this is used when running `prepare`, right?

**Comment by DrazenDodik** [comment]
I think this might be a bit of a bigger issue..

* I upload a file (`mydata.csv`) to Valohai from the UI
* I copy the datum URL
* Use that as a default input value in `valohai.prepare`
* When I run `vh exec run --adhoc mystep` it works fine
* I download the file (`mydata.csv`) to a local directory (`.valohai/mystep/inputs/`) so I can run the code locally
* `valohai-utils` can't map the datum URI to the filename.

So we'd need somehow a way where `valohai-utils` would call Valohai and ask what is the filename of that datum ID, and then use the local file with that name.

An additional hassle is that with that we'd just "trust" that the local file in the folder is that exact same version as the one where the datum points to (because we'd just checkfilename, nothing else). So then the question is, do we need to fetch the filename + checksums from Valohai, and compare them to the local file. If they match, then we use the local file, otherwise we throw a warning?

**Comment by magdapoppins** [comment]
What would be the benefit of having the file locally if it's anyway available to us remotely and we anyway need to validate it against the remote?

**Comment by DrazenDodik** [comment]
I want to be able to test my code locally. If `valohai-utils` can't resolve my inputs then my code doesn't work locally.

I'd put this in the nice to have bucket. There hasn't been that much demand for this feature and this still works if you use a `s3://` URI for example.
